apiVersion: v1
kind: Pod
metadata:
  name: seleniumapp
  labels:
    name: seleniumapp
spec:
  containers:
  - name: seleniumapp-container
    image: selenium/hub:latest
    ports:
      - containerPort: 4444
